# Generated by Django 4.1.3 on 2022-11-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convos', '0002_remove_conversation_friend_remove_conversation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
