# Generated by Django 4.1.3 on 2022-11-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convos', '0003_remove_message_receiver_remove_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversation', to='convos.conversation'),
        ),
    ]
