# Generated by Django 4.1.3 on 2022-12-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convos', '0005_alter_conversation_user1_alter_conversation_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='convos.message'),
        ),
    ]
