# Generated by Django 4.1.3 on 2022-12-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_post_owner_postlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlist',
            old_name='user',
            new_name='owner',
        ),
    ]
