# Generated by Django 4.1.3 on 2022-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_user_postlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='bookmarked_posts',
            field=models.ManyToManyField(null=True, related_name='bookmarked_posts', to='feed.post'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='liked_posts',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to='feed.post'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='reposted_posts',
            field=models.ManyToManyField(null=True, related_name='reposted_posts', to='feed.post'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='posts',
            field=models.ManyToManyField(null=True, related_name='post_list', to='feed.post'),
        ),
    ]
